from __future__ import annotations
from enum import StrEnum


class VerificationState(StrEnum):
    SELF_REPORTED = "SELF_REPORTED"
    OCR_PROPOSED = "OCR_PROPOSED"
    USER_CONFIRMED = "USER_CONFIRMED"
    HUMAN_REVIEWED = "HUMAN_REVIEWED"
    LAB_VERIFIED = "LAB_VERIFIED"
    CENTER_VERIFIED = "CENTER_VERIFIED"
    CONFLICT = "CONFLICT"
    UNKNOWN = "UNKNOWN"


class MediaQuality(StrEnum):
    HIGH_RES_AVAILABLE = "HIGH_RES_AVAILABLE"
    MEDIUM_RES_AVAILABLE = "MEDIUM_RES_AVAILABLE"
    THUMBNAIL_ONLY = "THUMBNAIL_ONLY"
    CROPPED = "CROPPED"
    OCCLUDED = "OCCLUDED"
    SCREENSHOT = "SCREENSHOT"
    UNREADABLE = "UNREADABLE"
